/* The following code was generated by JFlex 1.4.3 on 27.12.17 1:50 */

//imports
import java.util.regex.Pattern;
import java.util.List;
import java.util.LinkedList;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27.12.17 1:50 from the specification file
 * <tt>lex.jflex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\6\2\0\1\11\22\0\1\11\1\41\1\5\3\0"+
    "\1\34\1\3\2\10\1\10\1\10\1\10\1\10\1\0\1\10\1\1"+
    "\11\2\1\10\1\42\1\36\1\37\1\40\2\0\32\4\1\10\1\10"+
    "\1\10\1\0\1\7\1\0\1\17\1\21\1\15\1\32\1\24\1\25"+
    "\1\4\1\16\1\12\2\4\1\23\1\4\1\13\1\22\1\33\1\4"+
    "\1\20\1\26\1\14\1\30\1\31\1\27\3\4\1\10\1\35\1\10"+
    "\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\2\1\1\4\12\3"+
    "\2\1\3\4\1\1\3\0\1\3\1\5\13\3\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\15\3\1\20\1\21\1\22\2\3\1\23\5\3"+
    "\1\24\2\3\1\25\1\3\1\26\1\3\1\27\1\30"+
    "\3\3\1\31\4\3\1\32\1\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\43\0\106\0\151\0\214\0\257\0\322"+
    "\0\43\0\365\0\u0118\0\u013b\0\u015e\0\u0181\0\u01a4\0\u01c7"+
    "\0\u01ea\0\u020d\0\u0230\0\u0253\0\u0276\0\u0299\0\u02bc\0\u02df"+
    "\0\u0302\0\u0325\0\u0348\0\u036b\0\u038e\0\214\0\u03b1\0\u03d4"+
    "\0\u03f7\0\u041a\0\u043d\0\u0460\0\u0483\0\u04a6\0\u04c9\0\u04ec"+
    "\0\u050f\0\43\0\43\0\43\0\43\0\43\0\43\0\43"+
    "\0\43\0\43\0\214\0\u0532\0\u0555\0\u0578\0\u059b\0\u05be"+
    "\0\u05e1\0\u0604\0\u0627\0\u064a\0\u066d\0\u0690\0\u06b3\0\u06d6"+
    "\0\214\0\214\0\214\0\u06f9\0\u071c\0\214\0\u073f\0\u0762"+
    "\0\u0785\0\u07a8\0\u07cb\0\214\0\u07ee\0\u0811\0\214\0\u0834"+
    "\0\214\0\u0857\0\214\0\214\0\u087a\0\u089d\0\u08c0\0\214"+
    "\0\u08e3\0\u0906\0\u0929\0\u094c\0\214\0\214";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\6"+
    "\1\11\1\10\1\12\1\6\1\13\1\14\2\6\1\15"+
    "\1\16\2\6\1\17\1\20\1\6\1\21\1\6\1\22"+
    "\1\6\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\11\44\0\2\4\44\0\1\32\5\0\22\32\10\0"+
    "\2\6\1\0\1\6\2\0\1\6\2\0\22\6\7\0"+
    "\6\33\1\0\34\33\42\0\1\34\1\0\2\6\1\0"+
    "\1\6\2\0\1\6\2\0\1\6\1\35\11\6\1\36"+
    "\6\6\10\0\2\6\1\0\1\6\2\0\1\6\2\0"+
    "\6\6\1\37\13\6\10\0\2\6\1\0\1\6\2\0"+
    "\1\6\2\0\4\6\1\40\3\6\1\41\11\6\10\0"+
    "\2\6\1\0\1\6\2\0\1\6\2\0\12\6\1\42"+
    "\7\6\10\0\2\6\1\0\1\6\2\0\1\6\2\0"+
    "\10\6\1\43\11\6\10\0\2\6\1\0\1\6\2\0"+
    "\1\6\2\0\11\6\1\44\10\6\10\0\2\6\1\0"+
    "\1\6\2\0\1\6\2\0\5\6\1\45\10\6\1\46"+
    "\3\6\10\0\2\6\1\0\1\6\2\0\1\6\2\0"+
    "\4\6\1\47\15\6\10\0\2\6\1\0\1\6\2\0"+
    "\1\6\2\0\5\6\1\50\14\6\10\0\2\6\1\0"+
    "\1\6\2\0\1\6\2\0\6\6\1\51\13\6\43\0"+
    "\1\52\43\0\1\53\44\0\1\54\42\0\1\55\42\0"+
    "\1\56\42\0\1\57\6\0\1\60\44\0\1\61\35\0"+
    "\6\62\1\0\34\62\1\0\2\6\1\0\1\6\2\0"+
    "\1\6\2\0\2\6\1\63\16\6\1\64\10\0\2\6"+
    "\1\0\1\6\2\0\1\6\2\0\16\6\1\65\3\6"+
    "\10\0\2\6\1\0\1\6\2\0\1\6\2\0\5\6"+
    "\1\66\14\6\10\0\2\6\1\0\1\6\2\0\1\6"+
    "\2\0\20\6\1\67\1\6\10\0\2\6\1\0\1\6"+
    "\2\0\1\6\2\0\2\6\1\70\17\6\10\0\2\6"+
    "\1\0\1\6\2\0\1\6\2\0\10\6\1\71\11\6"+
    "\10\0\2\6\1\0\1\6\2\0\1\6\2\0\14\6"+
    "\1\72\5\6\10\0\2\6\1\0\1\6\2\0\1\6"+
    "\2\0\11\6\1\73\10\6\10\0\2\6\1\0\1\6"+
    "\2\0\1\6\2\0\1\6\1\74\20\6\10\0\2\6"+
    "\1\0\1\6\2\0\1\6\2\0\1\75\21\6\10\0"+
    "\2\6\1\0\1\6\2\0\1\6\2\0\6\6\1\76"+
    "\13\6\10\0\2\6\1\0\1\6\2\0\1\6\2\0"+
    "\1\77\21\6\10\0\2\6\1\0\1\6\2\0\1\6"+
    "\2\0\16\6\1\100\3\6\10\0\2\6\1\0\1\6"+
    "\2\0\1\6\2\0\12\6\1\101\7\6\10\0\2\6"+
    "\1\0\1\6\2\0\1\6\2\0\6\6\1\102\13\6"+
    "\10\0\2\6\1\0\1\6\2\0\1\6\2\0\12\6"+
    "\1\103\7\6\10\0\2\6\1\0\1\6\2\0\1\6"+
    "\2\0\16\6\1\104\3\6\10\0\2\6\1\0\1\6"+
    "\2\0\1\6\2\0\11\6\1\105\10\6\10\0\2\6"+
    "\1\0\1\6\2\0\1\6\2\0\12\6\1\106\7\6"+
    "\10\0\2\6\1\0\1\6\2\0\1\6\2\0\14\6"+
    "\1\107\5\6\10\0\2\6\1\0\1\6\2\0\1\6"+
    "\2\0\3\6\1\110\16\6\10\0\2\6\1\0\1\6"+
    "\2\0\1\6\2\0\11\6\1\111\10\6\10\0\2\6"+
    "\1\0\1\6\2\0\1\6\2\0\1\112\21\6\10\0"+
    "\2\6\1\0\1\6\2\0\1\6\2\0\1\6\1\113"+
    "\20\6\10\0\2\6\1\0\1\6\2\0\1\6\2\0"+
    "\2\6\1\114\17\6\10\0\2\6\1\0\1\6\2\0"+
    "\1\6\2\0\6\6\1\115\13\6\10\0\2\6\1\0"+
    "\1\6\2\0\1\6\2\0\12\6\1\116\7\6\10\0"+
    "\2\6\1\0\1\6\2\0\1\6\2\0\12\6\1\117"+
    "\7\6\10\0\2\6\1\0\1\6\2\0\1\6\2\0"+
    "\2\6\1\120\17\6\10\0\2\6\1\0\1\6\2\0"+
    "\1\6\2\0\12\6\1\121\7\6\10\0\2\6\1\0"+
    "\1\6\2\0\1\6\2\0\5\6\1\122\14\6\10\0"+
    "\2\6\1\0\1\6\2\0\1\6\2\0\2\6\1\123"+
    "\17\6\10\0\2\6\1\0\1\6\2\0\1\6\2\0"+
    "\1\6\1\124\20\6\10\0\2\6\1\0\1\6\2\0"+
    "\1\6\2\0\5\6\1\125\14\6\10\0\2\6\1\0"+
    "\1\6\2\0\1\6\2\0\1\126\21\6\10\0\2\6"+
    "\1\0\1\6\2\0\1\6\2\0\7\6\1\127\12\6"+
    "\10\0\2\6\1\0\1\6\2\0\1\6\2\0\1\6"+
    "\1\130\20\6\10\0\2\6\1\0\1\6\2\0\1\6"+
    "\2\0\10\6\1\131\11\6\10\0\2\6\1\0\1\6"+
    "\2\0\1\6\2\0\11\6\1\132\10\6\10\0\2\6"+
    "\1\0\1\6\2\0\1\6\2\0\1\6\1\133\20\6"+
    "\10\0\2\6\1\0\1\6\2\0\1\6\2\0\12\6"+
    "\1\134\7\6\10\0\2\6\1\0\1\6\2\0\1\6"+
    "\2\0\14\6\1\135\5\6\10\0\2\6\1\0\1\6"+
    "\2\0\1\6\2\0\14\6\1\136\5\6\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2415];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\1\11\20\1\3\0\15\1\11\11"+
    "\54\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }
	
enum Lexer {
	//for, do
	KEYWORD("KEYWORD"),
	// '(', ')', ':'
	DELIMETER("DELIMETER"),
	//variables
	VARIABLE("VARIABLE"),
	//:=, <, >, = etc
	OPERATION("OPERATION"),
	//some hex value
	NUMBER("NUMBER"),
	
	UNKNOWN("UNKNOWN");

	private final String value;

	Lexer(String value) {
		this.value = value;
	}

	String getType() {
		return value;
	}
}


	public static void print(Lexer lexer, String text, int atColumn) {
		System.out.printf("%s at column %d: %s\n", lexer.getType(), atColumn, text);	
	}


	static List<LinkedList<Integer>> table = new ArrayList<>(Arrays.asList(
		new LinkedList<>(),
		new LinkedList<>(),
		new LinkedList<>(),
		new LinkedList<>(),
		new LinkedList<>(),
		new LinkedList<>(),
		new LinkedList<>(),
		new LinkedList<>(),
		new LinkedList<>(),
		new LinkedList<>()
		)
	);

	public static boolean checkExists(Variable var) {
		return table.get(var.getHash() % 9).contains(var.getHash());
	} 

	public class Variable {

		private final String name;
		private final int hash;

		public Variable(String name, boolean create) {
			this.name = name;
			this.hash = hashCode();
			if (create) {
				addInTable();	
			}
		}

		private void addInTable() {
			if (!checkExists(this)) {
				table.get(hash % 9).add(hash);
			}/* else {
				throw new IllegalStateException("Переменная "+ this.name +" уже существует!");
			}*/
		}
		/**
		* ELF hash algorithm
		**/
		@Override
		public int hashCode() {
			int hash = 0, x, i;
			for (i = 0; i < name.length(); i++) {
				hash = (hash << 4) + (name.charAt(i));
				if ((x = hash & 0xF0000000) != 0) {
					hash ^= (x >> 24);
				}
				hash &= ~x;
			}
			return hash;
		}

		public String getName() {
			return name;
		}

		public int getHash() {
			return hash;
		}
	}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 122) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { print(Lexer.VARIABLE, yytext(), yycolumn);
	new Variable(yytext(), true);
	yyparser.yylval.sval = yytext();
	return Parser.VARIABLE;
          }
        case 28: break;
        case 1: 
          { System.out.print(yytext());
          }
        case 29: break;
        case 27: 
          { return Parser.VARBLOCK;
          }
        case 30: break;
        case 5: 
          { return Parser.IF;
          }
        case 31: break;
        case 17: 
          { return Parser.CHAR;
          }
        case 32: break;
        case 8: 
          { return Parser.LE_OP;
          }
        case 33: break;
        case 4: 
          { return (int) yycharat(0);
          }
        case 34: break;
        case 23: 
          { return Parser.PRINT;
          }
        case 35: break;
        case 12: 
          { yyparser.yylval.ival = (int) yycharat(0);
	return Parser.CHARACTER;
          }
        case 36: break;
        case 24: 
          { return Parser.RETURN;
          }
        case 37: break;
        case 19: 
          { return Parser.ELSE;
          }
        case 38: break;
        case 11: 
          { return Parser.NE_OP;
          }
        case 39: break;
        case 10: 
          { return Parser.GE_OP;
          }
        case 40: break;
        case 2: 
          { yyparser.yylval.ival = Integer.parseInt(yytext());
    return Parser.CONSTANT;
          }
        case 41: break;
        case 21: 
          { return Parser.FALSE;
          }
        case 42: break;
        case 7: 
          { return Parser.OR_OP;
          }
        case 43: break;
        case 16: 
          { return Parser.TRUE;
          }
        case 44: break;
        case 6: 
          { return Parser.AND_OP;
          }
        case 45: break;
        case 9: 
          { return Parser.EQ_OP;
          }
        case 46: break;
        case 25: 
          { return Parser.BOOLEAN;
          }
        case 47: break;
        case 22: 
          { return Parser.WHILE;
          }
        case 48: break;
        case 20: 
          { return Parser.INPUT;
          }
        case 49: break;
        case 18: 
          { return Parser.CODEBLOCK;
          }
        case 50: break;
        case 15: 
          { return Parser.INT;
          }
        case 51: break;
        case 26: 
          { return Parser.FUNCDEFBLOCK;
          }
        case 52: break;
        case 13: 
          { print(Lexer.VARIABLE, yytext(), yycolumn);
	new Variable(yytext(), true);
	yyparser.yylval.sval = yytext();
	return Parser.LITERAL;
          }
        case 53: break;
        case 14: 
          { System.out.println("Unknown character");
          }
        case 54: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Yylex <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Yylex scanner = null;
        try {
          scanner = new Yylex( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
